name: Feature Request
description: Suggest an idea for SHALOM
title: '[Feature] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your ideas for improving SHALOM!
  - type: textarea
    id: problem
    attributes:
      label: User Problem
      description: Is your feature request related to a problem? Please describe it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
