import copy
import logging
import re
import traceback
from pathlib import Path
from typing import Any, Optional, Tuple

from ase import Atoms
from pydantic import BaseModel

from shalom._config_loader import load_prompt
from shalom.backends.base import DFTBackend
from shalom.core.llm_provider import LLMProvider
from shalom.core.schemas import StructureReviewForm, RankedMaterial
from shalom.core.sandbox import SafeExecutor
from shalom.tools.ase_builder import ASEBuilder

logger = logging.getLogger(__name__)


class GeneratorResponse(BaseModel):
    """Python script schema generated by Geometry Generator."""

    python_code: str
    explanation: str


class GeometryGenerator:
    """Step 1 of the Simulation Layer: Geometry Generator.

    Writes an ASE Python script based on the natural language objective
    and target material (RankedMaterial) to generate the initial structure.
    """

    def __init__(self, llm_provider: LLMProvider):
        self.llm = llm_provider
        self.system_prompt = load_prompt("geometry_generator")

    def generate_code(
        self,
        target_objective: str,
        ranked_material: RankedMaterial,
        previous_feedback: str = "",
    ) -> GeneratorResponse:
        """Generate ASE Python code for the given objective and material.

        Args:
            target_objective: Natural language simulation objective.
            ranked_material: The winning material from the Design Layer.
            previous_feedback: Feedback from a previous failed attempt, if any.

        Returns:
            GeneratorResponse containing python_code and explanation.
        """
        user_prompt = (
            f"Target Objective: {target_objective}\n"
            f"Winner Material:\n{ranked_material.model_dump_json(indent=2)}\n\n"
        )
        if previous_feedback:
            user_prompt += (
                f"[CRITICAL FEEDBACK FROM REVIEWER]\n{previous_feedback}\n"
                "Please revise the code based on this feedback.\n\n"
            )
        user_prompt += "Please provide the Python code to generate the `atoms` object."

        return self.llm.generate_structured_output(
            system_prompt=self.system_prompt,
            user_prompt=user_prompt,
            response_model=GeneratorResponse,
        )


class FormFiller:
    """Step 2 of the Simulation Layer: Form Filler.

    Analyzes the Atoms object generated by the Geometry Generator to fill out
    a standardized review form (StructureReviewForm). Uses rule-based checks
    rather than an LLM for speed and determinism.
    """

    @staticmethod
    def evaluate_atoms(atoms: Atoms, filepath: Optional[str] = None) -> StructureReviewForm:
        """Evaluate an Atoms object and return a validation form.

        Args:
            atoms: The ASE Atoms object to evaluate.
            filepath: Optional path to the structure file.

        Returns:
            StructureReviewForm with validation results and feedback.
        """
        analysis = ASEBuilder.analyze_structure(atoms)

        num_atoms = analysis["num_atoms"]
        min_dist = analysis["minimum_distance"]
        vol = analysis["cell_volume"]

        is_valid = True
        feedback = "The structure appears physically valid."

        # Basic rule-based validation
        if num_atoms == 0:
            is_valid = False
            feedback = "Error: No atoms were generated."
        elif min_dist < 0.8 and num_atoms > 1:
            is_valid = False
            feedback = (
                f"Physical error: Interatomic distance is too short ({min_dist:.2f} A). "
                "Atoms may be overlapping."
            )
        elif vol > 10000:
            is_valid = False
            feedback = (
                f"Warning: Unit cell is too large (Volume: {vol:.1f} A^3). "
                "Simulation cost may be excessive."
            )

        # Vacuum layer check (approximate)
        vacuum_thickness = None
        cell = atoms.get_cell()
        positions = atoms.positions

        # Guard against non-3D cells or empty structures
        if len(cell) >= 3 and len(cell[2]) >= 3 and num_atoms > 0:
            if cell[2][2] > 10.0:
                z_positions = positions[:, 2]
                slab_thickness = z_positions.max() - z_positions.min()
                vacuum_thickness = cell[2][2] - slab_thickness

                if 0 < vacuum_thickness < 8.0:
                    is_valid = False
                    feedback = (
                        f"Warning: Vacuum layer ({vacuum_thickness:.1f} A) is too thin. "
                        "Periodic boundary interactions may occur (recommended >= 10 A)."
                    )

        return StructureReviewForm(
            file_path=filepath,
            num_atoms=num_atoms,
            cell_volume=vol,
            minimum_distance=min_dist,
            vacuum_thickness=vacuum_thickness,
            is_valid=is_valid,
            feedback=feedback,
        )


class GeometryReviewer:
    """Step 3 of the Simulation Layer: Geometry Reviewer (Control Loop Manager).

    Orchestrates the Generator -> exec -> FormFiller feedback loop,
    retrying up to ``max_retries`` times until a valid structure is produced.

    When a ``backend`` is provided, uses ``backend.write_input()`` to save
    structures in the backend's native format. Otherwise falls back to
    ``ASEBuilder.save_poscar()`` for backward compatibility.
    """

    def __init__(
        self,
        generator: GeometryGenerator,
        max_retries: int = 3,
        backend: Optional[DFTBackend] = None,
        vasp_config: Optional[Any] = None,
    ):
        self.generator = generator
        self.max_retries = max_retries
        self.backend = backend
        self.vasp_config = vasp_config

    def run_creation_loop(
        self, target_objective: str, ranked_material: RankedMaterial
    ) -> Tuple[bool, Optional[Atoms], str]:
        """Run the iterative structure creation and validation loop.

        Args:
            target_objective: Natural language simulation objective.
            ranked_material: The winning material from the Design Layer.

        Returns:
            A tuple of (success, atoms_or_none, filepath_or_error_message).
        """
        feedback = ""

        for attempt in range(self.max_retries):
            gen_response = self.generator.generate_code(target_objective, ranked_material, feedback)
            python_code = gen_response.python_code

            local_vars = {
                "bulk": ASEBuilder.construct_bulk,
                "surface": ASEBuilder.construct_surface,
            }

            try:
                updated_locals = SafeExecutor.execute(
                    python_code, local_vars=local_vars, timeout_seconds=15
                )

                if "atoms" not in updated_locals:
                    raise ValueError("Variable 'atoms' was not created. Please fix the code.")

                atoms = updated_locals["atoms"]
                form_result = FormFiller.evaluate_atoms(atoms)

                if form_result.is_valid:
                    output_dir = "generated_structures"
                    mat_name = re.sub(r'[^\w\-.]', '_', ranked_material.candidate.material_name)

                    if self.backend is not None:
                        write_params = {"filename": f"POSCAR_{mat_name}"}
                        if self.vasp_config is not None:
                            from shalom.backends.vasp_config import detect_and_apply_structure_hints
                            effective_config = copy.deepcopy(self.vasp_config)
                            detect_and_apply_structure_hints(atoms, effective_config)
                            write_params["config"] = effective_config
                        filepath = self.backend.write_input(
                            atoms, output_dir, **write_params
                        )
                    else:
                        filepath = ASEBuilder.save_poscar(
                            atoms, filename=f"POSCAR_{mat_name}", directory=output_dir
                        )
                    return True, atoms, filepath
                else:
                    feedback = form_result.feedback
                    logger.warning(
                        "[Attempt %d] Structure validation failed: %s",
                        attempt + 1,
                        feedback,
                    )

            except Exception as e:
                error_trace = traceback.format_exc()
                sanitized_trace = error_trace[-500:].replace(str(Path.home()), "~")
                feedback = (
                    f"Exception during Python execution:\n{e}\n\n"
                    f"Traceback (last 500 chars):\n{sanitized_trace}\n"
                    "Please check ASE syntax and produce a valid atoms object."
                )
                logger.warning("[Attempt %d] Code execution failed.", attempt + 1)

        return (
            False,
            None,
            f"Max retries ({self.max_retries}) exceeded. Last error: {feedback}",
        )
